#!/bin/bash

set_sddm_resolution(){
		monitor=$(xrandr | awk '/connected/ {print $1}')
		mode=$(xrandr | awk 'NR > 2 && NR < 4 {print $1}')
		mode=$(xrandr | awk 'NR > 2 && NR < 4 {print $2}' | sed 's/'*+'//')
		print_log -y "[DISPLAYMANAGER] " -b ":: " "setting sddm to respect monitors resolution"
sudo -i -u root bash <<EOF
echo "#!/bin/sh
# Xsetup - run as root before the login dialog appears
# This script is generated by hydotfiles/install_scripts/sddm_theme.sh

xrandr --output ${monitor} --mode ${mode} --rate ${rate}" > /usr/share/sddm/scripts/Xsetup"
EOF
}
